//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sprint_Zero.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int Id { get; set; }
        public string Movie { get; set; }
        public string Genre { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public string Price { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string url { get; set; }
        public byte[] Poster { get; set; }
        public Nullable<int> MovieId { get; set; }
    
        public virtual Movies Movy { get; set; }
    }
}
